# ServerListMotd Plugin by KennyTV
# Version ${project.version}

# The message shown in the multiplayer server list motd.
# If you put in multiple entries, one of them will be chosen randomly on every ping.
motds:
  - "&aWelcome!%NEWLINE%&6Just saying hello! :D"
 #- "Another entry"

# Is shown at the top right corner of the server in the serverlist,
# where the playercount would normally be displayed.
custom-playercountmessage: false
playercountmessage: "&4Hoia!"
# If set to false, only the given text will be shown without the playercount (requires custom-playercountmessage set to true).
show-playercount: true

# Is shown when you move your mouse above the text at the top right corner of the server in the serverlist,
# where the playercount would normally be displayed.
custom-playercounthovermessage: true
playercounthovermessage: "&cJoin%NEWLINE%&cplz"

# If you don't want to be up to date, you can!
update-checks: true

no-permission-message: "&cYou do not have the permission to execute that command."